// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  alternate_grid_2: dynamic(() => import("./AlternateGrid2")),
  blog: dynamic(() => import("./Blog")),
  call_to_action: dynamic(() => import("./CallToAction")),
  call_to_action_2: dynamic(() => import("./CallToAction2")),
  customer_logos: dynamic(() => import("./CustomerLogos")),
};
